spring:
  application:
    name: dolphin-boot-oauth
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/dolphin_boot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
#  redis:
#    cluster:
#      nodes: 10.101.71.132:7000,10.101.71.132:7001,10.101.71.133:7000,10.101.71.133:7001,10.101.71.134:7000,10.101.71.134:7001
#      max-redirects: 5
#    jedis:
#      pool:
#        # 资源池中最大连接数
#        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
#        max-active: 256
#        # 资源池运行最大空闲的连接数
#        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
#        max-idle: 256
#        # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
#        # 默认 -1 表示永不超时，设置5秒
#        max-wait: 5000